### ISSUE TITLE
Spread Negative Cases into the Future Iteratively?

### ISSUE THREAD

**Issue by hsbadr** [epiforecasts/covid-rt-brazil-subregional#1]
I think that the function `spread_negatives` assumes that negative new daily cases should be extracted from future cases while it could actually be due to fixing a reporting issue in the previous days (e.g., yesterday has a higher cumulative cases reported that's corrected today causing negative new cases).

**Comment by seabbs** [comment]
Yes, that is exactly the assumption (based on the data cleaning assumptions used by @paul-mee). Your correct that there are other totally valid assumptions (like spreading them backwards or discounting them). I think this choice is probably best informed by expert knowledge of the data and here @paul-mee and colleagues are probably the people to ask. Paul any thoughts on the best choice here?

**Comment by Paul-Mee** [comment]
Thanks for the comment. As You and Sam say there are a number of valid ways in which negative daily case counts can be resolved and it depends on how and why they are used in the particular dataset you are working with. We found  on visual examination of data for selected municipalities that in the Brazil.IO data (which collates data from Brazilian state ministries of health) large negative counts were soon corrected at least partially  by a large positive count on a subsequent day . Hence we chose to take the negative forward spreading approach with this dataset.

**Comment by seabbs** [comment]
This does make me think that a generalised version of this function would be helpful (i.e one that could do forwards, backwards or setting to zero based on expert knowledge) as it isn't the most obvious code to write. Perhaps it could sit in `EpiNow2`....

**Comment by hsbadr** [comment]
Thanks @Paul-Mee!

@seabbs Agreed. A generalized version of this can be exported from `EpiNow2`, with an option to deal with negative cases. For example, adding `negative_cases` as an integer argument where `negative_cases = 0` for excluding negative values (setting them to zero), `negative_cases = 1` for spreading them into the future (forward), or `negative_cases = -1` for backward spread.

**Comment by seabbs** [comment]
Yes sounds like a good idea (very happy to see an `EpiNow2` issue on this 😄 ). In general data cleaning heuristics are something we plan to look at but will have to be pushed to a later version I think as we don't really have the capacity at the moment.
